### ISSUE TITLE
Integrate Coveralls

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plotsbot#26]
Coveralls integration is something very platform / CI / testing library specific. Figure out a way to make it work.

**Comment by ananyo2012** [comment]
Yup I have setup it in Plots2 as well. Check documentation at https://coveralls.io. You can leave this to me. While you take care of more important issues

**Comment by ryzokuken** [comment]
@ananyo2012 Great. Thanks a lot.

**Comment by ryzokuken** [comment]
@ananyo2012 did you look it up?

**Comment by ananyo2012** [comment]
Ah I actually didn't get time to work on this. But you cab just leave this
one out or mark it as low priority and look on adding more features

On Jun 26, 2017 10:57 PM, "Ujjwal Sharma" <notifications@github.com> wrote:

@ananyo2012 <https://github.com/ananyo2012> did you look it up?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plotsbot/issues/26#issuecomment-311126302>,
or mute the thread

**Comment by bassdeveloper** [comment]
Can I take this up ?

**Comment by ryzokuken** [comment]
Sure, Rishabh. Just make sure @ananyo isn't working on it already.

**Comment by ananyo2012** [comment]
@bassdeveloper Sure go ahead. I didn't get time to work on it.

**Comment by ryzokuken** [comment]
@bassdeveloper How's the work going on this? Are you facing any issues?

**Comment by bassdeveloper** [comment]
@ryzokuken I haven't started work on this. I'm on it at this moment. I'll definitely post if I face issues.

**Comment by bassdeveloper** [comment]
#58
