### ISSUE TITLE
Use ESLint for linting the codebase

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plotsbot#6]
After a look into the various linting frameworks for Node JS (ESLint, JSHint, JSLint and JSCS, mainly). I have decided that ESLint seems to be our best option. Therefore, we should integrate ESLint with the project to maintain the sanity of the codabase. Integrating it this early on would also mean that we have to spend less time fixing linting issues later.

When it comes to the base config to use, we have a few options, including airbnb's, google's or facebook's ESLint config. Regarding this, I'd love to hear from the community, especially @publiclab/soc regarding which one they believe to be most appropriate for our project.

If you want to get started with contributing to this project and open source in general, this seems to be a great issue to start with. Follow the instructions on http://eslint.org/docs/user-guide/getting-started to get started with ESLint.

**Comment by ryzokuken** [comment]
@jywarren @ananyo2012 Does this issue seem okay for a `first-timers-only`?

**Comment by ananyo2012** [comment]
Yes I think this can be classified as a first-timers issue. Reading from the docs and setting it up seems a good task for first timers.

**Comment by ananyo2012** [comment]
I guess I can take this up. Since this is quite important and I also want to start contributing to the project :stuck_out_tongue: I guess this is fine by all?

**Comment by ryzokuken** [comment]
Yes. Please feel free.

**Comment by ryzokuken** [comment]
Yes. Please feel free.

**Comment by jywarren** [comment]
Hi, all - both because Ananyo is interested in it, and because it doesn't have quite the full checklist and welcoming documentation of our [other first-timers-only issues](https://github.com/publiclab/plots2/labels/first-timers-only), i'm removing the FTO label. I think it's a great one for `help-wanted` -- but it's not quite the easy few steps that might make a good FTO experience. Especially as it does require some bootstrapping of the setup, we'd like FTO issues to be a bit more guided. Thanks!

**Comment by ryzokuken** [comment]
@jywarren I got what you meant. In the future, I will make sure to include the checklist and a more comprehensive set of instructions in the first-timers-only issues.

Thanks.
