### ISSUE TITLE
config file path broken

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plotsbot#80]
Ever after #78, I started getting the error:
`Error: ENOENT: no such file or directory, open '../config.json'`

However, @codywill mentioned that the particular patch was required for the project to work in windows, however, it seems that for the bot to work in *nix systems, the original version worked fine (it was deployed on tycho already and worked fine on all our machines).

To fix this, we have three options: (current path - `../config.json`)
1. Go back to use the original `config.json` and temporarily break functionality on windows systems.
2. Use the slightly more appropriate sounding `\`${__dirname}/../config.json\``
3. Use a more cross-platform solution using the `path` module.

cc/ @jywarren @ananyo2012 @codywill

**Comment by codywill** [comment]
I just tried running the bot from within the `plotsbot` directory with `node ./src/bot.js` using the original `config.json` path and it worked fine. Previously I had been running the bot from `src` and it couldn't see `config.json`. I can investigate this further since the issue was caused by my change.

**Comment by ryzokuken** [comment]
Resolved in #81
